server:
    servlet:
      context-path: /spring-shop

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/supershop
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  thymeleaf:
    cache: false
files:
  storepath:
    images: "D:\\shop-images\\images"
    icons: "D:\\shop-images\\icons"